export const cakeList = [
  {
    id: 1,
    image: "images/choco7.png",
    name: "Choco Drip Var7",
    category: "Chocolate Drip Cake",
    featured: "YES",
    price: "700.00",
  },
  {
    id: 2,
    image: "images/character3.png",
    name: "Cartoon/Character cake Var3",
    category: "Cartoon/Chartacter Cake",
    featured: "YES",
    price: "600.00",
  },
  {
    id: 3,
    image: "images/theme8.png",
    name: "Themed Cake Var8",
    category: "Themed Cake",
    featured: "YES",
    price: "600.00",
  },
  {
    id: 4,
    image: "images/character7.png",
    name: "Cartoon/Character cake Var7",
    category: "Cartoon/Chartacter Cake",
    featured: "YES",
    price: "600.00",
  },
  {
    id: 5,
    image: "images/choco1.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 6,
    image: "images/choco2.png",
    name: "Choco Drip Var2",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 7,
    image: "images/choco3.png",
    name: "Choco Drip Var3",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 8,
    image: "images/choco4.png",
    name: "Choco Drip Var4",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 9,
    image: "images/choco5.png",
    name: "Choco Drip Var5",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 10,
    image: "images/choco6.png",
    name: "Choco Drip Var6",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 11,
    image: "images/choco8.png",
    name: "Choco Drip Var8",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 12,
    image: "images/choco9.png",
    name: "Choco Drip Var9",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 13,
    image: "images/choco10.png",
    name: "Choco Drip Var10",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 14,
    image: "images/choco11.png",
    name: "Choco Drip Var11",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 15,
    image: "images/choco12.png",
    name: "Choco Drip Var12",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 16,
    image: "images/theme1.png",
    name: "Themed Cake Var1",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 17,
    image: "images/theme2.png",
    name: "Themed Cake Var2",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 18,
    image: "images/theme3.png",
    name: "Themed Cake Var3",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 19,
    image: "images/theme4.png",
    name: "Themed Cake Var4",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 20,
    image: "images/theme5.png",
    name: "Themed Cake Var5",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 21,
    image: "images/theme6.png",
    name: "Themed Cake Var6",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 22,
    image: "images/theme7.png",
    name: "Themed Cake Var7",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 23,
    image: "images/theme9.png",
    name: "Themed Cake Var9",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 24,
    image: "images/theme10.png",
    name: "Themed Cake Var10",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 25,
    image: "images/theme11.png",
    name: "Themed Cake Var11",
    category: "Themed Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 26,
    image: "images/character1.png",
    name: "Cartoon/Character cake Var1",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 27,
    image: "images/character2.png",
    name: "Cartoon/Character cake Var2",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 28,
    image: "images/character4.png",
    name: "Cartoon/Character cake Var4",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 29,
    image: "images/character5.png",
    name: "Cartoon/Character cake Var5",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 30,
    image: "images/character6.png",
    name: "Cartoon/Character cake Var6",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 31,
    image: "images/character7.png",
    name: "Cartoon/Character cake Var7",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 32,
    image: "images/character8.png",
    name: "Cartoon/Character cake Var8",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 33,
    image: "images/character9.png",
    name: "Cartoon/Character cake Var9",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 34,
    image: "images/character10.png",
    name: "Cartoon/Character cake Var10",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 35,
    image: "images/character11.png",
    name: "Cartoon/Character cake Var11",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 36,
    image: "images/character12.png",
    name: "Cartoon/Character cake Var12",
    category: "Cartoon/Chartacter Cake",
    featured: "NO",
    price: "600.00",
  },
  {
    id: 37,
    image: "images/number1.png",
    name: "Number cake Var1",
    category: "Number Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 38,
    image: "images/number2.png",
    name: "Number cake Var2",
    category: "Number Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 39,
    image: "images/number3.png",
    name: "Number cake Var3",
    category: "Number Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 40,
    image: "images/number4.png",
    name: "Number cake Var4",
    category: "Number Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 41,
    image: "images/number5.png",
    name: "Number cake Var5",
    category: "Number Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 42,
    image: "images/number6.png",
    name: "Number cake Var6",
    category: "Number Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 43,
    image: "images/number7.png",
    name: "Number cake Var7",
    category: "Number Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 44,
    image: "images/number8.png",
    name: "Number cake Var8",
    category: "Number Cake",
    featured: "NO",
    price: "700.00",
  },
  {
    id: 45,
    image: "images/number9.png",
    name: "Number cake Var9",
    category: "Number Cake",
    featured: "NO",
    price: "700.00",
  },
];
