export const cakeList = [
  {
    id: 1,
    image: "images/choco1.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "P 600.00",
  },
  {
    id: 2,
    image: "images/theme1.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "YES",
    price: "P 600.00",
  },
  {
    id: 3,
    image: "images/character1.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "P 600.00",
  },
  {
    id: 4,
    image: "images/character2.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "P 600.00",
  },
  {
    id: 5,
    image: "images/character3.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "YES",
    price: "P 600.00",
  },
  {
    id: 6,
    image: "images/character4.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "P 600.00",
  },
  {
    id: 7,
    image: "images/choco2.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "P 600.00",
  },
  {
    id: 8,
    image: "images/choco12.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "YES",
    price: "P 600.00",
  },
  {
    id: 9,
    image: "images/theme2.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "NO",
    price: "P 600.00",
  },
  {
    id: 10,
    image: "images/character8.png",
    name: "Choco Drip Var1",
    category: "Chocolate Drip Cake",
    featured: "YES",
    price: "P 600.00",
  },
];

export const disclaimer = [
  {
    id: 1,
    disclaimer1: "Prices may vary according to sizes.",
    disclaimer2: "Prices may change without any prior notice.",
    disclaimer3: "Additional disclaimer: Actual food presentation may vary.",
  },
];
